import {  Inter,  Montserrat, Oxygen } from "next/font/google";

import "./globals.css";



const oxygen = Oxygen({
  subsets: ["latin"],
   weight: ["300", "400", "700"],
  variable: "--font-oxygen", 
});


const inter = Inter({
  subsets: ["latin"],

  variable: '--font-inter', 
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat', 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body
        className={` ${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
